// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp3cX6E1F_SmGqWs-ClEjDmCA852T7Tyw',
    appId: '1:536752711819:web:f1d10ea78dadc5e9110c8e',
    messagingSenderId: '536752711819',
    projectId: 'all-in-one-scheduler',
    authDomain: 'all-in-one-scheduler.firebaseapp.com',
    storageBucket: 'all-in-one-scheduler.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBykDP95SkoZmqlwUJReFnxRzwvpCoLuKg',
    appId: '1:536752711819:android:8fff93b61055222f110c8e',
    messagingSenderId: '536752711819',
    projectId: 'all-in-one-scheduler',
    storageBucket: 'all-in-one-scheduler.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0F_J16xC6q-lprCudCbHFYhxln60WzPc',
    appId: '1:536752711819:ios:7a4e0cdfcb3adb59110c8e',
    messagingSenderId: '536752711819',
    projectId: 'all-in-one-scheduler',
    storageBucket: 'all-in-one-scheduler.firebasestorage.app',
    iosClientId: '536752711819-4ajco97esddmc42djfuuu7pfa42f5iva.apps.googleusercontent.com',
    iosBundleId: 'com.example.allInOneScheduler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0F_J16xC6q-lprCudCbHFYhxln60WzPc',
    appId: '1:536752711819:ios:7a4e0cdfcb3adb59110c8e',
    messagingSenderId: '536752711819',
    projectId: 'all-in-one-scheduler',
    storageBucket: 'all-in-one-scheduler.firebasestorage.app',
    iosClientId: '536752711819-4ajco97esddmc42djfuuu7pfa42f5iva.apps.googleusercontent.com',
    iosBundleId: 'com.example.allInOneScheduler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp3cX6E1F_SmGqWs-ClEjDmCA852T7Tyw',
    appId: '1:536752711819:web:4f7ef2297e061150110c8e',
    messagingSenderId: '536752711819',
    projectId: 'all-in-one-scheduler',
    authDomain: 'all-in-one-scheduler.firebaseapp.com',
    storageBucket: 'all-in-one-scheduler.firebasestorage.app',
  );
}
